### PR TITLE
Rename Company parameter to Organization in the \experience command #3

### LINKED ISSUE #3: Rename `Company` parameter to `Organization` in the `\experience` command
Welcome to GitHub! This issue is reserved for people who have never contributed to an open-source project before. If that sounds like you, feel free to comment below to claim this issue as your own and I'll help walk you through the process of completing your very first contribution!

**The Problem**
[This line](https://github.com/jhale1805/expressive-resume/blob/main/README.md?plain=1#L67) of the `README.md` describes the parameters for the `\experience` command. Currently it names the second parameter `Company`, but a name like `Organization` would better include experience as a volunteer or working for a government organization. 

**The Solution**
1. Click the **Fork** button to make your own copy of this repository.
2. Open the `README.md` and click the pencil icon to edit it.
3. Find the line linked above and change the word `Company` to `Organization`.
4. **Commit** your change.
   - For the commit title, put the title of this issue.
   - For the description, go ahead and share your thoughts about making your first open-source contribution!
   - End the description with `Closes jhale1805/expressive-resume#3` to link your commit to this issue.
5. Open a **Pull Request**

From there, I will get a notification, at which point I will quickly double-check your changes and incorporate them into `expressive-resume`!

If you have questions about any of these steps or are feeling stuck, just comment your concern below and I'll jump in to give more detailed guidance. :D

### PR DESCRIPTION
**Pull request by iku12phycho**
Hi, @jhale1805.
This is my first open source contribution in GitHub.
I was a little nervous to contribute but I want to get used it in small steps.

Thank you.

ps. Thank you for your kind explanation. I recreated PR.

Closes jhale1805/expressive-resume#3

### CODE REVIEW

**Comment by thehale** [comment]
@iku12phycho Great job on figuring this part out!

The last step for this project is to follow the instructions in the comment from the **CLAassistant** regarding the Contributor License Agreement. The link in that comment also includes a summary of the agreement and its purpose, but, as always, feel free to ask me any questions you have about it!

**Comment by iku12phycho** [comment]
I really appreciate your help!!!

**Comment by thehale** [comment]
I see that you signed the CLA, so I merged in your change. You've officially completed your first open-source contribution! 🎉🎉

I'm happy to help! Hopefully you feel less nervous about contributing to this and/or other projects in the future 😄 .

**Comment by jhale1805** [comment]
Out of curiosity, how did you find this project?

I know there are some twitter bots that post about issues with the tags I used, but I didn't expect to get a response within just a few hours of creating the issue.

**Pull request merged**
